name: skin_care
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.0.3
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  flutter_riverpod: ^2.5.1
  gap: ^3.0.1
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  fl_chart: ^0.68.0
  cloud_firestore: ^4.17.3
  google_fonts: ^6.2.1
  auto_route: ^9.2.0
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  reorderable_grid: ^1.0.10
  firebase_storage: ^11.7.7
  intl: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^9.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/